
basic:
  seed: 2022
  data_path: '../../data/de_LDS_data.pkl'
  target_sub: 'sub_4'
  train_on_source: true
  train_ratio: 0.8
  do_quantization: false
  do_normalization: true
  quantization_level: 100
  model: 'LR'
  log_file: 'baseline.log'

model:
  SVC:
    C: 1e-4
    kernel: 'linear'
    degree: 3
    tol: 1e-4
    cache_size: 40960
    verbose: 0
    gamma: 'auto'
    decision_function_shape: 'ovr'

  LR:
    C: 1e-4
    tol: 1e-4
    solver: 'lbfgs'
    max_iter: 1000
    multi_class: 'ovr'
    verbose: 0
    n_cpu: 3

  ABC:
    n_estimators: 100
    learning_rate: 1.0
    algorithm: 'SAMME.R'

  LSVC:
    C: 1e-5
    tol: 1e-5
    loss: 'hinge'
    max_iter: 10000
    multi_class: 'ovr'
    verbose: 0


















