model:
  input_dim: 310
  num_classes: 3
  adaptation_param: 'auto'
# default: adaptation_param = 0.1


train:
  num_epochs: 200
  learning_rate: 1e-2
  # non default domain_learning_rate: 1e-4
  domain_loss_weight: 1.0
  weight_decay: 0.0
  batch_size: 64
  workers: 4
  adjust_learning_rate: true
  alpha: 10
  beta: 0.75
  gamma: 10
#  momentum: 0.9


basic:
  seed: 2022
  data_path: '../../data/data.pkl'
  target_sub: 'sub_1'
# default target_sub: 'sub_1'
  log_dir: 'log'


