
basic:
  seed: 2022
  data_path: '../../data/data.pkl'
  target_sub: 'sub_1'
# default target_sub: 'sub_1'
  log_dir: 'log'

model:
  input_dim: 310
  num_classes: 3

train:
  backbone:
    train_ratio: 0.8
    num_epochs: 50
    learning_rate: 1e-4
    weight_decay: 0.0
    batch_size: 64
    workers: 4


  classifier:
    train_ratio: 0.5
    checkpoint_dir: 'backbone_checkpoints'
    num_epochs: 100
    learning_rate: 1e-4
    weight_decay: 0.0
    batch_size: 64
    workers: 4








